name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name:  Hello World 1st Github Workflow Action
        run: echo "GitHub Actions Working  Hello World 1st Github Workflow Action"
